### ISSUE TITLE
Linux filesystem size claims seem wrong in the introduction

### ISSUE THREAD

**Issue by daenney** [jnoller/kubernaughty#1]
Reading through the introduction, the statement that Linux has a 2 TiB partition size limit strikes me as odd, and does not reflect the day to day reality I encounter running Linux systems.

> Linux also has a 2 TiB disk partition limit.

I believe the misunderstanding here arises from this being a limit due to a disk using an old MBR partition table layout instead of the modern and much more common place GPT. If you use a disk with an MBR partition table layout, then you won't be able to use more than 2TiB of the drive. This is also not unique to Linux, Windows would suffer the same limitation. Any partition or volume size limit would then be imposed by the filesystem, not the OS itself. In the case of ext4 that would be 1 EiB, XFS 8EiB and btrfs 16 EiB.

I also struggle with the following statement:

> You can add and have larger partitions, but most system daemons and applications will not be able to actually use the additional space

What would prevent system daemons and applications from being able to use the additional space? They might not have any need for it, but there's no technical limitation that I'm aware of that would prevent any system daemon or application using 20TiB of storage if it wanted to.

**Comment by jnoller** [comment]
@daenney Good points, this is still in progress (check the log) - specifically I mixed up  some guidance, let me update and fix that

**Comment by jnoller** [comment]
Ah, Yup - the issue is MBR and various VM generations - I totally missed adding this context:

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/faq-for-disks

Can I use GPT partitioning on an Azure Disk?

Generation 1 images can only use GPT partitioning on data disks, not OS disks. OS disks must use the MBR partition style.

Generation 2 images can use GPT partitioning on the OS disk as well as the data disks.

And:

What is the largest Managed disk size supported for operating system and data disks?

The partition type that Azure supports for an operating system disk is the master boot record (MBR). The MBR format supports a disk size up to 2 TiB. The largest size that Azure supports for an operating system disk is 2 TiB. Azure supports up to 32 TiB for managed data disks.

What is the largest Unmanaged Disk size supported for operating system and data disks?

The partition type that Azure supports for an operating system disk is the master boot record (MBR). The MBR format supports a disk size up to 2 TiB. The largest size that Azure supports for an operating system Unmanaged disk is 2 TiB. Azure supports up to 4 TiB for data Unmanaged disks.

What is the largest page blob size that's supported?

The largest page blob size that Azure supports is 8 TiB (8,191 GiB). The maximum page blob size when attached to a VM as data or operating system disks is 4 TiB (4,095 GiB).

Do I need to use a new version of Azure tools to create, attach, resize, and upload disks larger than 1 TiB?

You don't need to upgrade your existing Azure tools to create, attach, or resize disks larger than 1 TiB. To upload your VHD file from on-premises directly to Azure as a page blob or unmanaged disk, you need to use the latest tool sets listed below. We only support VHD uploads of up to 8 TiB.

**Comment by jnoller** [comment]
Self note - GPT vs MBR configurations also depending on the VM image (AMI, VHD) used if the underlying hypervisor supports GPT 

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/modify-volume-requirements.html#linux-volumes

**Comment by jnoller** [comment]
Derp fixed
